[package]
name = "testa-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
testa-core = { path = "../testa-core" }
testa-interpreter = { path = "../testa-interpreter" }
testa-generation = { path = "../testa-generation" }
testa-lsp = { path = "../testa-lsp" }
clap = { version = "4", features = ["derive"] }